version: "3.7"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
        - ../code:/workspace
  gra:
    image: grafana/grafana
    ports:
        - "3000:3000"
    volumes:
        - /var/lib/grafana
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: example
#    volumes:
#        - /var/lib/mysql
    cap_add:
      - SYS_NICE  # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
  adminer:
    image: adminer
    ports:
        - 8080:8080